
# This file was generated by 'versioneer.py' (0.27) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-10-26T13:31:46-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "526b98dc76329b68d6e0be697075910a049e9c15",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
